version: "3.9"
name: progserv2-todoapp
services:
  php_apache:
    container_name: php_apache
    image: php:8.1-apache
    volumes:
      - ./config:/var/config # config
      - ./public:/var/www/html # public
      - ./app:/var/www/app # app
      - ./database:/var/www/database # database
      - ./vendor:/var/www/vendor # vendor
    environment:
      - PHPRC=/var/config/php.ini
    ports:
      - 80:80
    depends_on:
      - mailHog
  mailHog:
    container_name: mailHog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
